# 核心任务

- name: memcached
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"} 
    - { role: role_cloud, tags: "role_cloud" } 
    - { role: memcached, tags: "memcached"}
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end" }

