# 服务器前置任务(ubuntu使用)
- name: memcached
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python


# # 核心任务

- name: memcached
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: memcached, tags: "memcached"}
